package entity;
// Generated 05-23-2015 03:08:47 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;



/**
 * Clientes generated by hbm2java
 */
@Entity
@Table(name="CLIENTES",schema="ROXMEL")
public class Clientes  implements java.io.Serializable {


     private BigDecimal carnet;
     private String nombre;
     private String apellidos;
     private String dui;

    public Clientes() {
    }

	
    public Clientes(BigDecimal carnet) {
        this.carnet = carnet;
    }
    public Clientes(BigDecimal carnet, String nombre, String apellidos, String dui) {
       this.carnet = carnet;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.dui = dui;
    }
   
    @Id  
    @GeneratedValue(strategy=GenerationType.SEQUENCE, generator="TRG")
    @SequenceGenerator(name="TRG", sequenceName = "Secuencia_clientes")
    @Column(name="CARNET", unique=true, nullable=false, precision=38, scale=0)
    public BigDecimal getCarnet() {
        return this.carnet;
    }
    
    public void setCarnet(BigDecimal carnet) {
        this.carnet = carnet;
    }

    
    @Column(name="NOMBRE", length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="APELLIDOS", length=50)
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    
    @Column(name="DUI", length=50)
    public String getDui() {
        return this.dui;
    }
    
    public void setDui(String dui) {
        this.dui = dui;
    }




}


